#ifndef METADATAPANEL_H
#define METADATAPANEL_H

#include "pqAutoGeneratedObjectPanel.h"
#include <QLabel>
#include <QLine>
#include <QLayout>

class ConePanel : public pqAutoGeneratedObjectPanel
{
  Q_OBJECT
public:
  ConePanel(pqProxy* pxy, QWidget* p)
    : pqAutoGeneratedObjectPanel(pxy, p)
  {
    this->layout()->addWidget(new QLabel("This is from a plugin", this));

  }
};



#endif // METADATAPANEL_H
